---
# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
project_name: github-audit-alerter
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod download
builds:
  - id: "github-audit-alerter"
    env:
      - GO111MODULE=on
      - CGO_ENABLED=0
    binary: ftw
    targets:
      - linux_amd64
      - linux_arm64
      - darwin_amd64
      - darwin_arm64
      - windows_amd64
archives:
  - format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: "{{ .ProjectName }}-checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  use: github
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: "Bug fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: Others
      order: 999
  filters:
    exclude:
      - "^docs"
      - "^test"
release:
  prerelease: auto
nfpms:
  - id: "github-audit-alerter"
    builds: ["github-audit-alerter"]
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    overrides:
      rpm:
        replacements:
          amd64: x86_64
        file_name_template: "{{ .ProjectName }}-{{ .Version }}.{{ .Arch }}"
      deb:
        file_name_template: "{{ .ProjectName }}-{{ .Version }}_{{ .Arch }}"
    vendor:
    homepage: https://github.com/chainguard-dev/github-audit-alerter
    maintainer: t+github@chainguard.dev
    description: >
      Send Slack alerts based on GitHub Audit Events, including two major categories of events:
        * Excessive repository clones by a single user
        * Unexpected events, such as a private repository being made public
      This is chiefly to detect whether or not someone's Github credentials have been abused for nefarious purposes, but can be used to notify on secrets shared on repos unintentionally made public.

    license: APL2

